// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm.proto

// Protobuf Java Version: 3.25.0
package com.cili.video.model.proto;

public final class DmProto {
  private DmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cili.video.model.proto.Dm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>sint64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>sint64 videoId = 3;</code>
     * @return The videoId.
     */
    long getVideoId();

    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string color = 5;</code>
     * @return The color.
     */
    java.lang.String getColor();
    /**
     * <code>string color = 5;</code>
     * @return The bytes for color.
     */
    com.google.protobuf.ByteString
        getColorBytes();

    /**
     * <code>sint32 fontSize = 6;</code>
     * @return The fontSize.
     */
    int getFontSize();

    /**
     * <code>sint32 stamp = 7;</code>
     * @return The stamp.
     */
    int getStamp();

    /**
     * <code>string createTime = 8;</code>
     * @return The createTime.
     */
    java.lang.String getCreateTime();
    /**
     * <code>string createTime = 8;</code>
     * @return The bytes for createTime.
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();
  }
  /**
   * Protobuf type {@code com.cili.video.model.proto.Dm}
   */
  public static final class Dm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cili.video.model.proto.Dm)
      DmOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dm.newBuilder() to construct.
    private Dm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dm() {
      content_ = "";
      color_ = "";
      createTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dm();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cili.video.model.proto.DmProto.internal_static_com_cili_video_model_proto_Dm_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cili.video.model.proto.DmProto.internal_static_com_cili_video_model_proto_Dm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cili.video.model.proto.DmProto.Dm.class, com.cili.video.model.proto.DmProto.Dm.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>sint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_ = 0L;
    /**
     * <code>sint64 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int VIDEOID_FIELD_NUMBER = 3;
    private long videoId_ = 0L;
    /**
     * <code>sint64 videoId = 3;</code>
     * @return The videoId.
     */
    @java.lang.Override
    public long getVideoId() {
      return videoId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object color_ = "";
    /**
     * <code>string color = 5;</code>
     * @return The color.
     */
    @java.lang.Override
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      }
    }
    /**
     * <code>string color = 5;</code>
     * @return The bytes for color.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FONTSIZE_FIELD_NUMBER = 6;
    private int fontSize_ = 0;
    /**
     * <code>sint32 fontSize = 6;</code>
     * @return The fontSize.
     */
    @java.lang.Override
    public int getFontSize() {
      return fontSize_;
    }

    public static final int STAMP_FIELD_NUMBER = 7;
    private int stamp_ = 0;
    /**
     * <code>sint32 stamp = 7;</code>
     * @return The stamp.
     */
    @java.lang.Override
    public int getStamp() {
      return stamp_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object createTime_ = "";
    /**
     * <code>string createTime = 8;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public java.lang.String getCreateTime() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <code>string createTime = 8;</code>
     * @return The bytes for createTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      java.lang.Object ref = createTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeSInt64(1, id_);
      }
      if (userId_ != 0L) {
        output.writeSInt64(2, userId_);
      }
      if (videoId_ != 0L) {
        output.writeSInt64(3, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, color_);
      }
      if (fontSize_ != 0) {
        output.writeSInt32(6, fontSize_);
      }
      if (stamp_ != 0) {
        output.writeSInt32(7, stamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, createTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, id_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, userId_);
      }
      if (videoId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, videoId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, color_);
      }
      if (fontSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, fontSize_);
      }
      if (stamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, stamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createTime_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, createTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cili.video.model.proto.DmProto.Dm)) {
        return super.equals(obj);
      }
      com.cili.video.model.proto.DmProto.Dm other = (com.cili.video.model.proto.DmProto.Dm) obj;

      if (getId()
          != other.getId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getVideoId()
          != other.getVideoId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getColor()
          .equals(other.getColor())) return false;
      if (getFontSize()
          != other.getFontSize()) return false;
      if (getStamp()
          != other.getStamp()) return false;
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + VIDEOID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVideoId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
      hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFontSize();
      hash = (37 * hash) + STAMP_FIELD_NUMBER;
      hash = (53 * hash) + getStamp();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.cili.video.model.proto.DmProto.Dm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.cili.video.model.proto.DmProto.Dm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cili.video.model.proto.DmProto.Dm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cili.video.model.proto.DmProto.Dm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cili.video.model.proto.Dm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cili.video.model.proto.Dm)
        com.cili.video.model.proto.DmProto.DmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cili.video.model.proto.DmProto.internal_static_com_cili_video_model_proto_Dm_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cili.video.model.proto.DmProto.internal_static_com_cili_video_model_proto_Dm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cili.video.model.proto.DmProto.Dm.class, com.cili.video.model.proto.DmProto.Dm.Builder.class);
      }

      // Construct using com.cili.video.model.proto.DmProto.Dm.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        userId_ = 0L;
        videoId_ = 0L;
        content_ = "";
        color_ = "";
        fontSize_ = 0;
        stamp_ = 0;
        createTime_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cili.video.model.proto.DmProto.internal_static_com_cili_video_model_proto_Dm_descriptor;
      }

      @java.lang.Override
      public com.cili.video.model.proto.DmProto.Dm getDefaultInstanceForType() {
        return com.cili.video.model.proto.DmProto.Dm.getDefaultInstance();
      }

      @java.lang.Override
      public com.cili.video.model.proto.DmProto.Dm build() {
        com.cili.video.model.proto.DmProto.Dm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cili.video.model.proto.DmProto.Dm buildPartial() {
        com.cili.video.model.proto.DmProto.Dm result = new com.cili.video.model.proto.DmProto.Dm(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.cili.video.model.proto.DmProto.Dm result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.videoId_ = videoId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.color_ = color_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.fontSize_ = fontSize_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.stamp_ = stamp_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.createTime_ = createTime_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cili.video.model.proto.DmProto.Dm) {
          return mergeFrom((com.cili.video.model.proto.DmProto.Dm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cili.video.model.proto.DmProto.Dm other) {
        if (other == com.cili.video.model.proto.DmProto.Dm.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getVideoId() != 0L) {
          setVideoId(other.getVideoId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getColor().isEmpty()) {
          color_ = other.color_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getFontSize() != 0) {
          setFontSize(other.getFontSize());
        }
        if (other.getStamp() != 0) {
          setStamp(other.getStamp());
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readSInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                userId_ = input.readSInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                videoId_ = input.readSInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                color_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                fontSize_ = input.readSInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                stamp_ = input.readSInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                createTime_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>sint64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>sint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>sint64 userId = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>sint64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long videoId_ ;
      /**
       * <code>sint64 videoId = 3;</code>
       * @return The videoId.
       */
      @java.lang.Override
      public long getVideoId() {
        return videoId_;
      }
      /**
       * <code>sint64 videoId = 3;</code>
       * @param value The videoId to set.
       * @return This builder for chaining.
       */
      public Builder setVideoId(long value) {

        videoId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 videoId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        videoId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object color_ = "";
      /**
       * <code>string color = 5;</code>
       * @return The color.
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string color = 5;</code>
       * @return The bytes for color.
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string color = 5;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        color_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string color = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        color_ = getDefaultInstance().getColor();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string color = 5;</code>
       * @param value The bytes for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        color_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int fontSize_ ;
      /**
       * <code>sint32 fontSize = 6;</code>
       * @return The fontSize.
       */
      @java.lang.Override
      public int getFontSize() {
        return fontSize_;
      }
      /**
       * <code>sint32 fontSize = 6;</code>
       * @param value The fontSize to set.
       * @return This builder for chaining.
       */
      public Builder setFontSize(int value) {

        fontSize_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 fontSize = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fontSize_ = 0;
        onChanged();
        return this;
      }

      private int stamp_ ;
      /**
       * <code>sint32 stamp = 7;</code>
       * @return The stamp.
       */
      @java.lang.Override
      public int getStamp() {
        return stamp_;
      }
      /**
       * <code>sint32 stamp = 7;</code>
       * @param value The stamp to set.
       * @return This builder for chaining.
       */
      public Builder setStamp(int value) {

        stamp_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 stamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        stamp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object createTime_ = "";
      /**
       * <code>string createTime = 8;</code>
       * @return The createTime.
       */
      public java.lang.String getCreateTime() {
        java.lang.Object ref = createTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createTime = 8;</code>
       * @return The bytes for createTime.
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        java.lang.Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createTime = 8;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        createTime_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        createTime_ = getDefaultInstance().getCreateTime();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string createTime = 8;</code>
       * @param value The bytes for createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        createTime_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cili.video.model.proto.Dm)
    }

    // @@protoc_insertion_point(class_scope:com.cili.video.model.proto.Dm)
    private static final com.cili.video.model.proto.DmProto.Dm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cili.video.model.proto.DmProto.Dm();
    }

    public static com.cili.video.model.proto.DmProto.Dm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dm>
        PARSER = new com.google.protobuf.AbstractParser<Dm>() {
      @java.lang.Override
      public Dm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Dm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dm> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cili.video.model.proto.DmProto.Dm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cili_video_model_proto_Dm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cili_video_model_proto_Dm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010dm.proto\022\032com.cili.video.model.proto\"\206" +
      "\001\n\002Dm\022\n\n\002id\030\001 \001(\022\022\016\n\006userId\030\002 \001(\022\022\017\n\007vid" +
      "eoId\030\003 \001(\022\022\017\n\007content\030\004 \001(\t\022\r\n\005color\030\005 \001" +
      "(\t\022\020\n\010fontSize\030\006 \001(\021\022\r\n\005stamp\030\007 \001(\021\022\022\n\nc" +
      "reateTime\030\010 \001(\tB%\n\032com.cili.video.model." +
      "protoB\007DmProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_cili_video_model_proto_Dm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cili_video_model_proto_Dm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cili_video_model_proto_Dm_descriptor,
        new java.lang.String[] { "Id", "UserId", "VideoId", "Content", "Color", "FontSize", "Stamp", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
