// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmlist.proto

// Protobuf Java Version: 3.25.0
package com.cili.video.model.proto;

public final class DmListProto {
  private DmListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DmListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cili.video.model.proto.DmList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    java.util.List<DmProto.Dm>
        getDmListList();
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    DmProto.Dm getDmList(int index);
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    int getDmListCount();
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    java.util.List<? extends DmProto.DmOrBuilder>
        getDmListOrBuilderList();
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    DmProto.DmOrBuilder getDmListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.cili.video.model.proto.DmList}
   */
  public static final class DmList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cili.video.model.proto.DmList)
      DmListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DmList.newBuilder() to construct.
    private DmList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DmList() {
      dmList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DmList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DmListProto.internal_static_com_cili_video_model_proto_DmList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DmListProto.internal_static_com_cili_video_model_proto_DmList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DmList.class, Builder.class);
    }

    public static final int DMLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<DmProto.Dm> dmList_;
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    @Override
    public java.util.List<DmProto.Dm> getDmListList() {
      return dmList_;
    }
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    @Override
    public java.util.List<? extends DmProto.DmOrBuilder>
        getDmListOrBuilderList() {
      return dmList_;
    }
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    @Override
    public int getDmListCount() {
      return dmList_.size();
    }
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    @Override
    public DmProto.Dm getDmList(int index) {
      return dmList_.get(index);
    }
    /**
     * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
     */
    @Override
    public DmProto.DmOrBuilder getDmListOrBuilder(
        int index) {
      return dmList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dmList_.size(); i++) {
        output.writeMessage(1, dmList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dmList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dmList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DmList)) {
        return super.equals(obj);
      }
      DmList other = (DmList) obj;

      if (!getDmListList()
          .equals(other.getDmListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDmListCount() > 0) {
        hash = (37 * hash) + DMLIST_FIELD_NUMBER;
        hash = (53 * hash) + getDmListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DmList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DmList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static DmList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static DmList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DmList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DmList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DmList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cili.video.model.proto.DmList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cili.video.model.proto.DmList)
        DmListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DmListProto.internal_static_com_cili_video_model_proto_DmList_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DmListProto.internal_static_com_cili_video_model_proto_DmList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DmList.class, Builder.class);
      }

      // Construct using com.cili.video.model.proto.DmListProto.DmList.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (dmListBuilder_ == null) {
          dmList_ = java.util.Collections.emptyList();
        } else {
          dmList_ = null;
          dmListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DmListProto.internal_static_com_cili_video_model_proto_DmList_descriptor;
      }

      @Override
      public DmList getDefaultInstanceForType() {
        return DmList.getDefaultInstance();
      }

      @Override
      public DmList build() {
        DmList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DmList buildPartial() {
        DmList result = new DmList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(DmList result) {
        if (dmListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dmList_ = java.util.Collections.unmodifiableList(dmList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dmList_ = dmList_;
        } else {
          result.dmList_ = dmListBuilder_.build();
        }
      }

      private void buildPartial0(DmList result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DmList) {
          return mergeFrom((DmList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DmList other) {
        if (other == DmList.getDefaultInstance()) return this;
        if (dmListBuilder_ == null) {
          if (!other.dmList_.isEmpty()) {
            if (dmList_.isEmpty()) {
              dmList_ = other.dmList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDmListIsMutable();
              dmList_.addAll(other.dmList_);
            }
            onChanged();
          }
        } else {
          if (!other.dmList_.isEmpty()) {
            if (dmListBuilder_.isEmpty()) {
              dmListBuilder_.dispose();
              dmListBuilder_ = null;
              dmList_ = other.dmList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dmListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDmListFieldBuilder() : null;
            } else {
              dmListBuilder_.addAllMessages(other.dmList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                DmProto.Dm m =
                    input.readMessage(
                        DmProto.Dm.parser(),
                        extensionRegistry);
                if (dmListBuilder_ == null) {
                  ensureDmListIsMutable();
                  dmList_.add(m);
                } else {
                  dmListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<DmProto.Dm> dmList_ =
        java.util.Collections.emptyList();
      private void ensureDmListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dmList_ = new java.util.ArrayList<DmProto.Dm>(dmList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DmProto.Dm, DmProto.Dm.Builder, DmProto.DmOrBuilder> dmListBuilder_;

      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public java.util.List<DmProto.Dm> getDmListList() {
        if (dmListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dmList_);
        } else {
          return dmListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public int getDmListCount() {
        if (dmListBuilder_ == null) {
          return dmList_.size();
        } else {
          return dmListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public DmProto.Dm getDmList(int index) {
        if (dmListBuilder_ == null) {
          return dmList_.get(index);
        } else {
          return dmListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder setDmList(
          int index, DmProto.Dm value) {
        if (dmListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDmListIsMutable();
          dmList_.set(index, value);
          onChanged();
        } else {
          dmListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder setDmList(
          int index, DmProto.Dm.Builder builderForValue) {
        if (dmListBuilder_ == null) {
          ensureDmListIsMutable();
          dmList_.set(index, builderForValue.build());
          onChanged();
        } else {
          dmListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder addDmList(DmProto.Dm value) {
        if (dmListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDmListIsMutable();
          dmList_.add(value);
          onChanged();
        } else {
          dmListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder addDmList(
          int index, DmProto.Dm value) {
        if (dmListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDmListIsMutable();
          dmList_.add(index, value);
          onChanged();
        } else {
          dmListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder addDmList(
          DmProto.Dm.Builder builderForValue) {
        if (dmListBuilder_ == null) {
          ensureDmListIsMutable();
          dmList_.add(builderForValue.build());
          onChanged();
        } else {
          dmListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder addDmList(
          int index, DmProto.Dm.Builder builderForValue) {
        if (dmListBuilder_ == null) {
          ensureDmListIsMutable();
          dmList_.add(index, builderForValue.build());
          onChanged();
        } else {
          dmListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder addAllDmList(
          Iterable<? extends DmProto.Dm> values) {
        if (dmListBuilder_ == null) {
          ensureDmListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dmList_);
          onChanged();
        } else {
          dmListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder clearDmList() {
        if (dmListBuilder_ == null) {
          dmList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dmListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public Builder removeDmList(int index) {
        if (dmListBuilder_ == null) {
          ensureDmListIsMutable();
          dmList_.remove(index);
          onChanged();
        } else {
          dmListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public DmProto.Dm.Builder getDmListBuilder(
          int index) {
        return getDmListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public DmProto.DmOrBuilder getDmListOrBuilder(
          int index) {
        if (dmListBuilder_ == null) {
          return dmList_.get(index);  } else {
          return dmListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public java.util.List<? extends DmProto.DmOrBuilder>
           getDmListOrBuilderList() {
        if (dmListBuilder_ != null) {
          return dmListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dmList_);
        }
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public DmProto.Dm.Builder addDmListBuilder() {
        return getDmListFieldBuilder().addBuilder(
            DmProto.Dm.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public DmProto.Dm.Builder addDmListBuilder(
          int index) {
        return getDmListFieldBuilder().addBuilder(
            index, DmProto.Dm.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cili.video.model.proto.Dm dmList = 1;</code>
       */
      public java.util.List<DmProto.Dm.Builder>
           getDmListBuilderList() {
        return getDmListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DmProto.Dm, DmProto.Dm.Builder, DmProto.DmOrBuilder>
          getDmListFieldBuilder() {
        if (dmListBuilder_ == null) {
          dmListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DmProto.Dm, DmProto.Dm.Builder, DmProto.DmOrBuilder>(
                  dmList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dmList_ = null;
        }
        return dmListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cili.video.model.proto.DmList)
    }

    // @@protoc_insertion_point(class_scope:com.cili.video.model.proto.DmList)
    private static final DmList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DmList();
    }

    public static DmList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DmList>
        PARSER = new com.google.protobuf.AbstractParser<DmList>() {
      @Override
      public DmList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DmList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DmList> getParserForType() {
      return PARSER;
    }

    @Override
    public DmList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cili_video_model_proto_DmList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cili_video_model_proto_DmList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014dmlist.proto\022\032com.cili.video.model.pro" +
      "to\032\010Dm.proto\"8\n\006DmList\022.\n\006dmList\030\001 \003(\0132\036" +
      ".com.cili.video.model.proto.DmB)\n\032com.ci" +
      "li.video.model.protoB\013DmListProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          DmProto.getDescriptor(),
        });
    internal_static_com_cili_video_model_proto_DmList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cili_video_model_proto_DmList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cili_video_model_proto_DmList_descriptor,
        new String[] { "DmList", });
    DmProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
